export const BASE_URL =
  "https://cors-anywhere.herokuapp.com/https://covid-bod.herokuapp.com/";

export const FETCH_CLASSES_START = "FETCH_CLASSES_START";
export const FETCH_CLASSES_SUCCESS = "FETCH_CLASSES_SUCCESS";
export const FETCH_CLASSES_FAILURE = "FETCH_CLASSES_FAILURE";
export const ADD_CLASS_START = "ADD_CLASS_START";
export const ADD_CLASS_SUCCESS = "ADD_CLASS_SUCCESS";
export const ADD_CLASS_FAILURE = "ADD_CLASS_FAILURE";
export const EDIT_CLASS_START = "EDIT_CLASS_START";
export const EDIT_CLASS_SUCCESS = "EDIT_CLASS_SUCCESS";
export const EDIT_CLASS_FAILURE = "EDIT_CLASS_FAILURE";
export const DELETE_CLASS_START = "DELETE_CLASS_START";
export const DELETE_CLASS_SUCCESS = "DELETE_CLASS_SUCCESS";
export const DELETE_CLASS_FAILURE = "DELETE_CLASS_FAILURE";

export const FETCH_ATTENDEES_START = "FETCH_ATTENDEES_START";
export const FETCH_ATTENDEES_SUCCESS = "FETCH_ATTENDEES_SUCCESS";
export const FETCH_ATTENDEES_FAILURE = "FETCH_ATTENDEES_FAILURE";
export const ENROLL_IN_CLASS_START = "ENROLL_IN_CLASS_START";
export const ENROLL_IN_CLASS_SUCCESS = "ENROLL_IN_CLASS_SUCCESS";
export const ENROLL_IN_CLASS_FAILURE = "ENROLL_IN_CLASS_FAILURE";

export const FETCH_USER_START = "FETCH_USER_START";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAILURE = "FETCH_USER_FAILURE";

export const userActionTypes = {
  FETCH_USER_START,
  FETCH_USER_SUCCESS,
  FETCH_USER_FAILURE,
};

export const attendeesActionTypes = {
  FETCH_ATTENDEES_START,
  FETCH_ATTENDEES_SUCCESS,
  FETCH_ATTENDEES_FAILURE,
  ENROLL_IN_CLASS_START,
  ENROLL_IN_CLASS_SUCCESS,
  ENROLL_IN_CLASS_FAILURE,
};

const classActionTypes = {
  FETCH_CLASSES_START,
  FETCH_CLASSES_SUCCESS,
  FETCH_CLASSES_FAILURE,
  ADD_CLASS_START,
  ADD_CLASS_SUCCESS,
  ADD_CLASS_FAILURE,
  EDIT_CLASS_START,
  EDIT_CLASS_SUCCESS,
  EDIT_CLASS_FAILURE,
  DELETE_CLASS_START,
  DELETE_CLASS_SUCCESS,
  DELETE_CLASS_FAILURE,
};
export default classActionTypes;
